### ISSUE TITLE
Wrong output with the example input

### ISSUE THREAD

**Issue by LuckyPigeon** [JackKuo-tw/shudu#2]
## Description

I use two example input but get unexpected answer. Here's the output screenshot.
![image](https://user-images.githubusercontent.com/32315294/95192384-b258fd80-0804-11eb-8815-62be6ceebac5.png)

## Steps to Reproduce

```shell=bash
cd shudu/
npm i
node index.js 鼠标在手,光标跟我走!
```

## Versions

* node: 12.18.4
* npm: 6.14.6
* npx: 6.14.6

**Comment by LuckyPigeon** [comment]
@JackKuo-tw 
Can I send a PR after I solved this issue?

**Comment by LuckyPigeon** [comment]
@JackKuo-tw 
I have success with this code. Could I make a PR with it?
![image](https://user-images.githubusercontent.com/32315294/95220352-f5c56300-0828-11eb-99e1-446246bf3064.png)

**Comment by JackKuo-tw** [comment]
Thanks for your report! 😊
