### ISSUE TITLE
微博在轉換後，有些功能會失效

### ISSUE THREAD

**Issue by abc0922001** [JackKuo-tw/shudu#7]
轉換後，切換標籤、留言、轉發、按讚等功能都不能用
在轉換前都是可以用的

步驟
1. https://m.weibo.cn/beta （可以不登入）
2. 點擊 shudu （設定沒改）
3. 原本可以點進去該條微博，也點不進去了

**Comment by abc0922001** [comment]
Chromium 85.0.4183.121
OS : windows 10 1903

**Comment by JackKuo-tw** [comment]
感謝回報。
關於這類問題應是那些按鈕是使用 JS 綁定事件觸發的（網頁載入時只做一次），舒讀重寫 DOM 後沒有重新綁定事件觸發因此會失效。
這部分我有一些嘗試解法，最近忙碩論可能不太會部署新版。

**Comment by JackKuo-tw** [comment]
碩士口試順利結束了，此問題也在 56635020fddd643ae5d30e4b642d485f8a5ef2ff 中修復了，已經安排 v1.3 上架到，靜候佳音。
